"""

Revision ID: f0b9ec4cd155
Revises: 87a657309cf0
Create Date: 2022-03-21 07:30:23.435719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0b9ec4cd155"
down_revision = "87a657309cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reviews_car_id_fkey", "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "cars", ["car_id"], ["id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key("reviews_car_id_fkey", "reviews", "cars", ["car_id"], ["id"])
    # ### end Alembic commands ###
